#
# \brief Default Travis for the Empty Project
# \author Leon Ezequiel D.
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo pip install conan
  - sudo apt-get install -qq valgrind

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -DTRAVISCI=ON
  - cmake --build . --config release
  - cd bin
  - valgrind --leak-check=full --error-exitcode=1 --trace-children=yes --show-leak-kinds=all ./test-empty-template
  - cd ..
  - make utest
  - sudo make install

branches:
  only:
    - master
    - develop
